version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=processing_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: uvicorn backend.asgi:application --host 0.0.0.1 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/processing_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  event_consumer:
    build: .
    command: python manage.py run_event_consumer
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/processing_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
