# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: processing/proto/jobs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'processing/proto/jobs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprocessing/proto/jobs.proto\x12\x04jobs\"\'\n\x05Stage\x12\r\n\x05stage\x18\x01 \x01(\t\x12\x0f\n\x07variant\x18\x02 \x01(\t\"i\n\x10\x43reateJobRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\x11\n\tcontenido\x18\x03 \x01(\t\x12$\n\x0fpipeline_config\x18\x04 \x03(\x0b\x32\x0b.jobs.Stage\"2\n\x11\x43reateJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x1f\n\rGetJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\x84\x01\n\nJobMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0c\n\x04tipo\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x14\n\x0cresults_json\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t\">\n\x0eGetJobResponse\x12\x1d\n\x03job\x18\x01 \x01(\x0b\x32\x10.jobs.JobMessage\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\x7f\n\nJobService\x12<\n\tCreateJob\x12\x16.jobs.CreateJobRequest\x1a\x17.jobs.CreateJobResponse\x12\x33\n\x06GetJob\x12\x13.jobs.GetJobRequest\x1a\x14.jobs.GetJobResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processing.proto.jobs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STAGE']._serialized_start=37
  _globals['_STAGE']._serialized_end=76
  _globals['_CREATEJOBREQUEST']._serialized_start=78
  _globals['_CREATEJOBREQUEST']._serialized_end=183
  _globals['_CREATEJOBRESPONSE']._serialized_start=185
  _globals['_CREATEJOBRESPONSE']._serialized_end=235
  _globals['_GETJOBREQUEST']._serialized_start=237
  _globals['_GETJOBREQUEST']._serialized_end=268
  _globals['_JOBMESSAGE']._serialized_start=271
  _globals['_JOBMESSAGE']._serialized_end=403
  _globals['_GETJOBRESPONSE']._serialized_start=405
  _globals['_GETJOBRESPONSE']._serialized_end=467
  _globals['_JOBSERVICE']._serialized_start=469
  _globals['_JOBSERVICE']._serialized_end=596
# @@protoc_insertion_point(module_scope)
